version: '3'
services:
  api:
    build: api
    command: "node src/index"      
    ports:
      - "3001:3001"
    environment:
      PORT: 3001
      HOST: 127.0.0.1
      MONGO_URL: mongodb://api_db:27017/my_db
    depends_on:
      - api_db
  api_db:
    image: "mongo:latest"
    volumes: 
     - mongodb_api:/data/db
volumes: 
  mongodb_api: 